# Site settings
title            : Vincent Knight
email            : vincent.knight@gmail.com
description      : "Class website for Game Theory"
baseurl          : "/Year_3_game_theory_course"
url              : "http://drvinceknight.github.io"
github_username  : "drvinceknight"
twitter_username : "@drvinceknight"
plus_username    : "+VincentKnight"
blogurl          : "http://drvinceknight.github.io/unpeudemath/"

# Build settings
markdown    : kramdown
permalink   : pretty
highlighter : pygments
